package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Alumno;
import es.fplumara.dam1.alumnos.model.Curso;
import es.fplumara.dam1.alumnos.model.TipoOrden;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class CursoRepositoryDB implements CursoRepository{

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }
    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }
    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS cursos (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  activo boolean,
                  nombre varchar(10)
                );
                """;
        try{
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);
            } catch (SQLException e) {
            throw new RuntimeException("Error inicializado en schemma ", e);
        }
    }

    @Override
    public Optional<Curso> findById(Integer id) {
        if (id == null) {
            return Optional.empty();
        }
        String sql = "SELECT id, estado , nombre  FROM Curso WHERE id = ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            if(!rs.next()){
                return Optional.empty();
            }
            return Optional.of(mapClase(rs));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public List<Curso> findAll() {
        String sql = "SELECT id,activo, nombre FROM cursos ORDER BY id";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            List<Curso> curso = new ArrayList<>();
            while (rs.next()) {
                curso.add();
            }
            return curso;

        } catch (SQLException e) {
            throw new RuntimeException("Error listando cursos", e);
        }
    }

    @Override
    public Curso insert(Curso curso) {
        if( curso == null)
            throw new IllegalArgumentException("El curso no puede ser null");


    }

    @Override
    public Curso update(Curso curso) {
        return null;
    }

    @Override
    public void deletePorNombre(String texto) {
        String sql = "DELETE from cursos where nombre like %?%";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, texto);

            ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException("Error eliminando cursos", e);
        }
    }

    @Override
    public List<Curso> listarPorEstado(boolean estado) {

        String sql = "select * from cursos where activo = ?";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setBoolean(1, estado);

            ResultSet rs = ps.executeQuery();

            List<Curso> cursos = new ArrayList<>();

            while (rs.next()){
                Curso curso = new Curso();
                curso.setId(rs.getInt("id"));
                curso.setNombre(rs.getString("nombre"));
                curso.setEstado(rs.getBoolean("activo"));

                curso.add(curso);
            }

            return cursos;
        } catch (SQLException e) {
            throw new RuntimeException("Error listado por estado", e);
        }

    }

    @Override
    public List<Curso> listarOrdenadoPor(String curso, TipoOrden TipoOrden) {

        return List.of();
    }
}
